server:
  port: 8081
fraudcheck:
  url: http://fraudcheck-service

security:
  basic:
    enabled: false
management:
  security:
    enabled: false
rabbitmq:
  uri: amqp://guest:guest@localhost
  request-queue: my-rabbit-queue
  response-queue: response-queue

spring:
  application:
    name: cpg-apigateway
  cloud:
    stream:
      bindings:
        output:
          destination: request-queue